import pickle

AWL= {\
"abandon": 1,\
"abandoned": 1,\
"abandoning": 1,\
"abandonment": 1,\
"abandons": 1,\
"abnormal": 1,\
"abnormally": 1,\
"abstract": 1,\
"abstraction": 1,\
"abstractions": 1,\
"abstractly": 1,\
"abstracts": 1,\
"academia": 1,\
"academic": 1,\
"academically": 1,\
"academics": 1,\
"academies": 1,\
"academy": 1,\
"access": 1,\
"accessed": 1,\
"accesses": 1,\
"accessibility": 1,\
"accessible": 1,\
"accessing": 1,\
"accommodate": 1,\
"accommodated": 1,\
"accommodates": 1,\
"accommodating": 1,\
"accommodation": 1,\
"accompanied": 1,\
"accompanies": 1,\
"accompaniment": 1,\
"accompany": 1,\
"accompanying": 1,\
"accumulate": 1,\
"accumulated": 1,\
"accumulates": 1,\
"accumulating": 1,\
"accumulation": 1,\
"accuracy": 1,\
"accurate": 1,\
"accurately": 1,\
"achievable": 1,\
"achieve": 1,\
"achieved": 1,\
"achievement": 1,\
"achievements": 1,\
"achieves": 1,\
"achieving": 1,\
"acknowledge": 1,\
"acknowledged": 1,\
"acknowledgemens": 1,\
"acknowledgement": 1,\
"acknowledges": 1,\
"acknowledging": 1,\
"acquire": 1,\
"acquired": 1,\
"acquires": 1,\
"acquiring": 1,\
"acquisition": 1,\
"acquisitions": 1,\
"adapt": 1,\
"adaptability": 1,\
"adaptable": 1,\
"adaptation": 1,\
"adaptations": 1,\
"adapted": 1,\
"adapting": 1,\
"adaptive": 1,\
"adapts": 1,\
"adequacy": 1,\
"adequate": 1,\
"adequately": 1,\
"adjacent": 1,\
"adjust": 1,\
"adjusted": 1,\
"adjusting": 1,\
"adjustment": 1,\
"adjustments": 1,\
"adjusts": 1,\
"administrate": 1,\
"administrates": 1,\
"administration": 1,\
"administrations": 1,\
"administrative": 1,\
"administratively": 1,\
"administrator": 1,\
"administrators": 1,\
"adult": 1,\
"adulthood": 1,\
"adults": 1,\
"advocacy": 1,\
"advocate": 1,\
"advocated": 1,\
"advocates": 1,\
"advocating": 1,\
"affect": 1,\
"affected": 1,\
"affecting": 1,\
"affective": 1,\
"affectively": 1,\
"affects": 1,\
"aggregate": 1,\
"aggregated": 1,\
"aggregates": 1,\
"aggregating": 1,\
"aggregation": 1,\
"aid": 1,\
"aided": 1,\
"aiding": 1,\
"aids": 1,\
"albeit": 1,\
"allocate": 1,\
"allocated": 1,\
"allocates": 1,\
"allocating": 1,\
"allocation": 1,\
"allocations": 1,\
"alter": 1,\
"alterable": 1,\
"alteration": 1,\
"alterations": 1,\
"altered": 1,\
"altering": 1,\
"alternate": 1,\
"alternating": 1,\
"alternative": 1,\
"alternatively": 1,\
"alternatives": 1,\
"alters": 1,\
"ambiguities": 1,\
"ambiguity": 1,\
"ambiguous": 1,\
"amend": 1,\
"amended": 1,\
"amending": 1,\
"amendment": 1,\
"amendments": 1,\
"amends": 1,\
"analogies": 1,\
"analogous": 1,\
"analogy": 1,\
"analyse": 1,\
"analysed": 1,\
"analyser": 1,\
"analysers": 1,\
"analyses": 1,\
"analysing": 1,\
"analysis": 1,\
"analyst": 1,\
"analysts": 1,\
"analytic": 1,\
"analytical": 1,\
"analytically": 1,\
"analyze": 1,\
"analyzed": 1,\
"analyzes": 1,\
"analyzing": 1,\
"annual": 1,\
"annually": 1,\
"anticipate": 1,\
"anticipated": 1,\
"anticipates": 1,\
"anticipating": 1,\
"anticipation": 1,\
"apparent": 1,\
"apparently": 1,\
"append": 1,\
"appended": 1,\
"appendices": 1,\
"appending": 1,\
"appendix": 1,\
"appendixes": 1,\
"appends": 1,\
"appreciable": 1,\
"appreciably": 1,\
"appreciate": 1,\
"appreciated": 1,\
"appreciates": 1,\
"appreciating": 1,\
"appreciation": 1,\
"approach": 1,\
"approachable": 1,\
"approached": 1,\
"approaches": 1,\
"approaching": 1,\
"appropriacy": 1,\
"appropriate": 1,\
"appropriately": 1,\
"appropriateness": 1,\
"approximate": 1,\
"approximated": 1,\
"approximately": 1,\
"approximates": 1,\
"approximating": 1,\
"approximation": 1,\
"approximations": 1,\
"arbitrarily": 1,\
"arbitrariness": 1,\
"arbitrary": 1,\
"area": 1,\
"areas": 1,\
"aspect": 1,\
"aspects": 1,\
"assemble": 1,\
"assembled": 1,\
"assembles": 1,\
"assemblies": 1,\
"assembling": 1,\
"assembly": 1,\
"assess": 1,\
"assessable": 1,\
"assessed": 1,\
"assesses": 1,\
"assessing": 1,\
"assessment": 1,\
"assessments": 1,\
"assign": 1,\
"assigned": 1,\
"assigning": 1,\
"assignment": 1,\
"assignments": 1,\
"assigns": 1,\
"assist": 1,\
"assistance": 1,\
"assistant": 1,\
"assistants": 1,\
"assisted": 1,\
"assisting": 1,\
"assists": 1,\
"assume": 1,\
"assumed": 1,\
"assumes": 1,\
"assuming": 1,\
"assumption": 1,\
"assumptions": 1,\
"assurance": 1,\
"assurances": 1,\
"assure": 1,\
"assured": 1,\
"assuredly": 1,\
"assures": 1,\
"assuring": 1,\
"attach": 1,\
"attached": 1,\
"attaches": 1,\
"attaching": 1,\
"attachment": 1,\
"attachments": 1,\
"attain": 1,\
"attainable": 1,\
"attained": 1,\
"attaining": 1,\
"attainment": 1,\
"attainments": 1,\
"attains": 1,\
"attitude": 1,\
"attitudes": 1,\
"attributable": 1,\
"attribute": 1,\
"attributed": 1,\
"attributes": 1,\
"attributing": 1,\
"attribution": 1,\
"author": 1,\
"authored": 1,\
"authoring": 1,\
"authoritative": 1,\
"authorities": 1,\
"authority": 1,\
"authors": 1,\
"authorship": 1,\
"automate": 1,\
"automated": 1,\
"automates": 1,\
"automatic": 1,\
"automatically": 1,\
"automating": 1,\
"automation": 1,\
"availability": 1,\
"available": 1,\
"aware": 1,\
"awareness": 1,\
"behalf": 1,\
"beneficial": 1,\
"beneficiaries": 1,\
"beneficiary": 1,\
"benefit": 1,\
"benefited": 1,\
"benefiting": 1,\
"benefits": 1,\
"bias": 1,\
"biased": 1,\
"biases": 1,\
"biasing": 1,\
"bond": 1,\
"bonded": 1,\
"bonding": 1,\
"bonds": 1,\
"brevity": 1,\
"brief": 1,\
"briefed": 1,\
"briefing": 1,\
"briefly": 1,\
"briefs": 1,\
"bulk": 1,\
"bulky": 1,\
"capabilities": 1,\
"capability": 1,\
"capable": 1,\
"capacities": 1,\
"capacity": 1,\
"categories": 1,\
"categorisation": 1,\
"categorise": 1,\
"categorised": 1,\
"categorises": 1,\
"categorising": 1,\
"categorization": 1,\
"categorized": 1,\
"categorizes": 1,\
"categorizing": 1,\
"category": 1,\
"cease": 1,\
"ceased": 1,\
"ceaseless": 1,\
"ceases": 1,\
"ceasing": 1,\
"challenge": 1,\
"challenged": 1,\
"challenger": 1,\
"challengers": 1,\
"challenges": 1,\
"challenging": 1,\
"channel": 1,\
"channelled": 1,\
"channelling": 1,\
"channels": 1,\
"chapter": 1,\
"chapters": 1,\
"chart": 1,\
"charted": 1,\
"charting": 1,\
"charts": 1,\
"chemical": 1,\
"chemically": 1,\
"chemicals": 1,\
"circumstance": 1,\
"circumstances": 1,\
"citation": 1,\
"citations": 1,\
"cite": 1,\
"cited": 1,\
"cites": 1,\
"citing": 1,\
"civil": 1,\
"clarification": 1,\
"clarified": 1,\
"clarifies": 1,\
"clarify": 1,\
"clarifying": 1,\
"clarity": 1,\
"classic": 1,\
"classical": 1,\
"classics": 1,\
"clause": 1,\
"clauses": 1,\
"co-operate": 1,\
"co-ordinate": 1,\
"code": 1,\
"coded": 1,\
"codes": 1,\
"coding": 1,\
"coherence": 1,\
"coherent": 1,\
"coherently": 1,\
"coincide": 1,\
"coincided": 1,\
"coincidence": 1,\
"coincidences": 1,\
"coincident": 1,\
"coincidental": 1,\
"coincides": 1,\
"coinciding": 1,\
"collapse": 1,\
"collapsed": 1,\
"collapses": 1,\
"collapsible": 1,\
"collapsing": 1,\
"colleague": 1,\
"colleagues": 1,\
"commence": 1,\
"commenced": 1,\
"commencement": 1,\
"commences": 1,\
"commencing": 1,\
"comment": 1,\
"commentaries": 1,\
"commentary": 1,\
"commentator": 1,\
"commentators": 1,\
"commented": 1,\
"commenting": 1,\
"comments": 1,\
"commission": 1,\
"commissioned": 1,\
"commissioner": 1,\
"commissioners": 1,\
"commissioning": 1,\
"commissions": 1,\
"commit": 1,\
"commitment": 1,\
"commitments": 1,\
"commits": 1,\
"committed": 1,\
"committing": 1,\
"commodities": 1,\
"commodity": 1,\
"communicable": 1,\
"communicate": 1,\
"communicated": 1,\
"communicates": 1,\
"communicating": 1,\
"communication": 1,\
"communications": 1,\
"communicative": 1,\
"communicatively": 1,\
"communities": 1,\
"community": 1,\
"compatibility": 1,\
"compatible": 1,\
"compensate": 1,\
"compensated": 1,\
"compensates": 1,\
"compensating": 1,\
"compensation": 1,\
"compensations": 1,\
"compensatory": 1,\
"compilation": 1,\
"compilations": 1,\
"compile": 1,\
"compiled": 1,\
"compiles": 1,\
"compiling": 1,\
"complement": 1,\
"complementary": 1,\
"complemented": 1,\
"complementing": 1,\
"complements": 1,\
"complex": 1,\
"complexities": 1,\
"complexity": 1,\
"component": 1,\
"componentry": 1,\
"components": 1,\
"compound": 1,\
"compounded": 1,\
"compounding": 1,\
"compounds": 1,\
"comprehensive": 1,\
"comprehensively": 1,\
"comprise": 1,\
"comprised": 1,\
"comprises": 1,\
"comprising": 1,\
"computable": 1,\
"computation": 1,\
"computational": 1,\
"computations": 1,\
"compute": 1,\
"computed": 1,\
"computer": 1,\
"computerised": 1,\
"computers": 1,\
"computing": 1,\
"conceivable": 1,\
"conceivably": 1,\
"conceive": 1,\
"conceived": 1,\
"conceives": 1,\
"conceiving": 1,\
"concentrate": 1,\
"concentrated": 1,\
"concentrates": 1,\
"concentrating": 1,\
"concentration": 1,\
"concept": 1,\
"conception": 1,\
"concepts": 1,\
"conceptual": 1,\
"conceptualisation": 1,\
"conceptualise": 1,\
"conceptualised": 1,\
"conceptualises": 1,\
"conceptualising": 1,\
"conceptually": 1,\
"conclude": 1,\
"concluded": 1,\
"concludes": 1,\
"concluding": 1,\
"conclusion": 1,\
"conclusions": 1,\
"conclusive": 1,\
"conclusively": 1,\
"concurrent": 1,\
"concurrently": 1,\
"conduct": 1,\
"conducted": 1,\
"conducting": 1,\
"conducts": 1,\
"confer": 1,\
"conference": 1,\
"conferences": 1,\
"conferred": 1,\
"conferring": 1,\
"confers": 1,\
"confine": 1,\
"confined": 1,\
"confines": 1,\
"confining": 1,\
"confirm": 1,\
"confirmation": 1,\
"confirmed": 1,\
"confirming": 1,\
"confirms": 1,\
"conflict": 1,\
"conflicted": 1,\
"conflicting": 1,\
"conflicts": 1,\
"conform": 1,\
"conformability": 1,\
"conformable": 1,\
"conformance": 1,\
"conformation": 1,\
"conformed": 1,\
"conforming": 1,\
"conformist": 1,\
"conformists": 1,\
"conformity": 1,\
"conforms": 1,\
"consensus": 1,\
"consent": 1,\
"consented": 1,\
"consenting": 1,\
"consents": 1,\
"consequence": 1,\
"consequences": 1,\
"consequent": 1,\
"consequently": 1,\
"considerable": 1,\
"considerably": 1,\
"consist": 1,\
"consisted": 1,\
"consistency": 1,\
"consistent": 1,\
"consistently": 1,\
"consisting": 1,\
"consists": 1,\
"constancy": 1,\
"constant": 1,\
"constantly": 1,\
"constants": 1,\
"constituencies": 1,\
"constituency": 1,\
"constituent": 1,\
"constituents": 1,\
"constitute": 1,\
"constituted": 1,\
"constitutes": 1,\
"constituting": 1,\
"constitution": 1,\
"constitutional": 1,\
"constitutionally": 1,\
"constitutions": 1,\
"constitutive": 1,\
"constrain": 1,\
"constrained": 1,\
"constraining": 1,\
"constrains": 1,\
"constraint": 1,\
"constraints": 1,\
"construct": 1,\
"constructed": 1,\
"constructing": 1,\
"construction": 1,\
"constructions": 1,\
"constructive": 1,\
"constructs": 1,\
"consult": 1,\
"consultancy": 1,\
"consultant": 1,\
"consultants": 1,\
"consultation": 1,\
"consultations": 1,\
"consultative": 1,\
"consulted": 1,\
"consulting": 1,\
"consults": 1,\
"consume": 1,\
"consumed": 1,\
"consumer": 1,\
"consumers": 1,\
"consumes": 1,\
"consuming": 1,\
"consumption": 1,\
"contact": 1,\
"contactable": 1,\
"contacted": 1,\
"contacting": 1,\
"contacts": 1,\
"contemporaries": 1,\
"contemporary": 1,\
"context": 1,\
"contexts": 1,\
"contextual": 1,\
"contextualise": 1,\
"contextualised": 1,\
"contextualising": 1,\
"contextualize": 1,\
"contextualized": 1,\
"contextualizing": 1,\
"contract": 1,\
"contracted": 1,\
"contracting": 1,\
"contractor": 1,\
"contractors": 1,\
"contracts": 1,\
"contradict": 1,\
"contradicted": 1,\
"contradicting": 1,\
"contradiction": 1,\
"contradictions": 1,\
"contradictory": 1,\
"contradicts": 1,\
"contrarily": 1,\
"contrary": 1,\
"contrast": 1,\
"contrasted": 1,\
"contrasting": 1,\
"contrastive": 1,\
"contrasts": 1,\
"contribute": 1,\
"contributed": 1,\
"contributes": 1,\
"contributing": 1,\
"contribution": 1,\
"contributions": 1,\
"contributor": 1,\
"contributors": 1,\
"controversial": 1,\
"controversially": 1,\
"controversies": 1,\
"controversy": 1,\
"convene": 1,\
"convened": 1,\
"convenes": 1,\
"convening": 1,\
"convention": 1,\
"conventional": 1,\
"conventionally": 1,\
"conventions": 1,\
"converse": 1,\
"conversely": 1,\
"conversion": 1,\
"conversions": 1,\
"convert": 1,\
"converted": 1,\
"convertible": 1,\
"converting": 1,\
"converts": 1,\
"convince": 1,\
"convinced": 1,\
"convinces": 1,\
"convincing": 1,\
"convincingly": 1,\
"cooperate": 1,\
"cooperated": 1,\
"cooperates": 1,\
"cooperating": 1,\
"cooperation": 1,\
"cooperative": 1,\
"cooperatively": 1,\
"coordinate": 1,\
"coordinated": 1,\
"coordinates": 1,\
"coordinating": 1,\
"coordination": 1,\
"coordinator": 1,\
"coordinators": 1,\
"core": 1,\
"cored": 1,\
"cores": 1,\
"coring": 1,\
"corporate": 1,\
"corporates": 1,\
"corporation": 1,\
"corporations": 1,\
"correspond": 1,\
"corresponded": 1,\
"correspondence": 1,\
"corresponding": 1,\
"correspondingly": 1,\
"corresponds": 1,\
"couple": 1,\
"coupled": 1,\
"couples": 1,\
"coupling": 1,\
"co‑operated": 1,\
"co‑operates": 1,\
"co‑operation": 1,\
"co‑operative": 1,\
"co‑operatively": 1,\
"co‑ordinated": 1,\
"co‑ordinates": 1,\
"co‑ordinating": 1,\
"co‑ordination": 1,\
"co‑ordinator": 1,\
"co‑ordinators": 1,\
"create": 1,\
"created": 1,\
"creates": 1,\
"creating": 1,\
"creation": 1,\
"creations": 1,\
"creative": 1,\
"creatively": 1,\
"creativity": 1,\
"creator": 1,\
"creators": 1,\
"credit": 1,\
"credited": 1,\
"crediting": 1,\
"creditor": 1,\
"creditors": 1,\
"credits": 1,\
"criteria": 1,\
"criterion": 1,\
"crucial": 1,\
"crucially": 1,\
"cultural": 1,\
"culturally": 1,\
"culture": 1,\
"cultured": 1,\
"cultures": 1,\
"currencies": 1,\
"currency": 1,\
"cycle": 1,\
"cycled": 1,\
"cycles": 1,\
"cyclic": 1,\
"cyclical": 1,\
"cycling": 1,\
"data": 1,\
"debatable": 1,\
"debate": 1,\
"debated": 1,\
"debates": 1,\
"debating": 1,\
"decade": 1,\
"decades": 1,\
"decline": 1,\
"declined": 1,\
"declines": 1,\
"declining": 1,\
"deduce": 1,\
"deduced": 1,\
"deduces": 1,\
"deducing": 1,\
"deduction": 1,\
"deductions": 1,\
"definable": 1,\
"define": 1,\
"defined": 1,\
"defines": 1,\
"defining": 1,\
"definite": 1,\
"definitely": 1,\
"definition": 1,\
"definitions": 1,\
"definitive": 1,\
"demonstrable": 1,\
"demonstrably": 1,\
"demonstrate": 1,\
"demonstrated": 1,\
"demonstrates": 1,\
"demonstrating": 1,\
"demonstration": 1,\
"demonstrations": 1,\
"demonstrative": 1,\
"demonstratively": 1,\
"demonstrator": 1,\
"demonstrators": 1,\
"deniable": 1,\
"denial": 1,\
"denials": 1,\
"denied": 1,\
"denies": 1,\
"denotation": 1,\
"denotations": 1,\
"denote": 1,\
"denoted": 1,\
"denotes": 1,\
"denoting": 1,\
"deny": 1,\
"denying": 1,\
"depress": 1,\
"depressed": 1,\
"depresses": 1,\
"depressing": 1,\
"depression": 1,\
"deregister": 1,\
"deregistered": 1,\
"deregistering": 1,\
"deregisters": 1,\
"deregistration": 1,\
"deregulated": 1,\
"deregulates": 1,\
"deregulating": 1,\
"deregulation": 1,\
"derivation": 1,\
"derivations": 1,\
"derivative": 1,\
"derivatives": 1,\
"derive": 1,\
"derived": 1,\
"derives": 1,\
"deriving": 1,\
"design": 1,\
"designed": 1,\
"designer": 1,\
"designers": 1,\
"designing": 1,\
"designs": 1,\
"despite": 1,\
"detect": 1,\
"detectable": 1,\
"detected": 1,\
"detecting": 1,\
"detection": 1,\
"detective": 1,\
"detectives": 1,\
"detector": 1,\
"detectors": 1,\
"detects": 1,\
"deviate": 1,\
"deviated": 1,\
"deviates": 1,\
"deviating": 1,\
"deviation": 1,\
"deviations": 1,\
"device": 1,\
"devices": 1,\
"devote": 1,\
"devoted": 1,\
"devotedly": 1,\
"devotes": 1,\
"devoting": 1,\
"devotion": 1,\
"devotions": 1,\
"differentiate": 1,\
"differentiated": 1,\
"differentiates": 1,\
"differentiating": 1,\
"differentiation": 1,\
"dimension": 1,\
"dimensional": 1,\
"dimensions": 1,\
"diminish": 1,\
"diminished": 1,\
"diminishes": 1,\
"diminishing": 1,\
"diminution": 1,\
"discrete": 1,\
"discretely": 1,\
"discretion": 1,\
"discretionary": 1,\
"discriminate": 1,\
"discriminated": 1,\
"discriminates": 1,\
"discriminating": 1,\
"discrimination": 1,\
"disestablish": 1,\
"disestablished": 1,\
"disestablishes": 1,\
"disestablishing": 1,\
"disestablishment": 1,\
"displace": 1,\
"displaced": 1,\
"displacement": 1,\
"displaces": 1,\
"displacing": 1,\
"display": 1,\
"displayed": 1,\
"displaying": 1,\
"displays": 1,\
"disposable": 1,\
"disposal": 1,\
"dispose": 1,\
"disposed": 1,\
"disposes": 1,\
"disposing": 1,\
"disproportion": 1,\
"disproportionate": 1,\
"disproportionately": 1,\
"dissimilar": 1,\
"distinct": 1,\
"distinction": 1,\
"distinctions": 1,\
"distinctive": 1,\
"distinctively": 1,\
"distinctly": 1,\
"distort": 1,\
"distorted": 1,\
"distorting": 1,\
"distortion": 1,\
"distortions": 1,\
"distorts": 1,\
"distribute": 1,\
"distributed": 1,\
"distributing": 1,\
"distribution": 1,\
"distributional": 1,\
"distributions": 1,\
"distributive": 1,\
"distributor": 1,\
"distributors": 1,\
"diverse": 1,\
"diversely": 1,\
"diversification": 1,\
"diversified": 1,\
"diversifies": 1,\
"diversify": 1,\
"diversifying": 1,\
"diversity": 1,\
"document": 1,\
"documentation": 1,\
"documented": 1,\
"documenting": 1,\
"documents": 1,\
"domain": 1,\
"domains": 1,\
"domestic": 1,\
"domestically": 1,\
"domesticate": 1,\
"domesticated": 1,\
"domesticating": 1,\
"domestics": 1,\
"dominance": 1,\
"dominant": 1,\
"dominate": 1,\
"dominated": 1,\
"dominates": 1,\
"dominating": 1,\
"domination": 1,\
"draft": 1,\
"drafted": 1,\
"drafting": 1,\
"drafts": 1,\
"drama": 1,\
"dramas": 1,\
"dramatic": 1,\
"dramatically": 1,\
"dramatisation": 1,\
"dramatisations": 1,\
"dramatise": 1,\
"dramatised": 1,\
"dramatises": 1,\
"dramatising": 1,\
"dramatist": 1,\
"dramatists": 1,\
"dramatization": 1,\
"dramatizations": 1,\
"dramatize": 1,\
"dramatized": 1,\
"dramatizes": 1,\
"dramatizing": 1,\
"duration": 1,\
"dynamic": 1,\
"dynamically": 1,\
"dynamics": 1,\
"economic": 1,\
"economical": 1,\
"economically": 1,\
"economics": 1,\
"economies": 1,\
"economist": 1,\
"economists": 1,\
"economy": 1,\
"edit": 1,\
"edited": 1,\
"editing": 1,\
"edition": 1,\
"editions": 1,\
"editor": 1,\
"editorial": 1,\
"editorials": 1,\
"editors": 1,\
"edits": 1,\
"element": 1,\
"elements": 1,\
"eliminate": 1,\
"eliminated": 1,\
"eliminates": 1,\
"eliminating": 1,\
"elimination": 1,\
"emerge": 1,\
"emerged": 1,\
"emergence": 1,\
"emergent": 1,\
"emerges": 1,\
"emerging": 1,\
"emphasis": 1,\
"emphasise": 1,\
"emphasised": 1,\
"emphasising": 1,\
"emphasize": 1,\
"emphasized": 1,\
"emphasizes": 1,\
"emphasizing": 1,\
"emphatic": 1,\
"emphatically": 1,\
"empirical": 1,\
"empirically": 1,\
"empiricism": 1,\
"enable": 1,\
"enabled": 1,\
"enables": 1,\
"enabling": 1,\
"encounter": 1,\
"encountered": 1,\
"encountering": 1,\
"encounters": 1,\
"energetic": 1,\
"energetically": 1,\
"energies": 1,\
"energy": 1,\
"enforce": 1,\
"enforced": 1,\
"enforcement": 1,\
"enforces": 1,\
"enforcing": 1,\
"enhance": 1,\
"enhanced": 1,\
"enhancement": 1,\
"enhances": 1,\
"enhancing": 1,\
"enormity": 1,\
"enormous": 1,\
"enormously": 1,\
"ensure": 1,\
"ensured": 1,\
"ensures": 1,\
"ensuring": 1,\
"entities": 1,\
"entity": 1,\
"environment": 1,\
"environmental": 1,\
"environmentalist": 1,\
"environmentalists": 1,\
"environmentally": 1,\
"environments": 1,\
"equate": 1,\
"equated": 1,\
"equates": 1,\
"equating": 1,\
"equation": 1,\
"equations": 1,\
"equip": 1,\
"equipment": 1,\
"equipped": 1,\
"equipping": 1,\
"equips": 1,\
"equivalence": 1,\
"equivalent": 1,\
"erode": 1,\
"eroded": 1,\
"erodes": 1,\
"eroding": 1,\
"erosion": 1,\
"erroneous": 1,\
"erroneously": 1,\
"error": 1,\
"errors": 1,\
"establish": 1,\
"established": 1,\
"establishes": 1,\
"establishing": 1,\
"establishment": 1,\
"establishments": 1,\
"estate": 1,\
"estates": 1,\
"estimate": 1,\
"estimated": 1,\
"estimates": 1,\
"estimating": 1,\
"estimation": 1,\
"estimations": 1,\
"ethic": 1,\
"ethical": 1,\
"ethically": 1,\
"ethics": 1,\
"ethnic": 1,\
"ethnicity": 1,\
"evaluate": 1,\
"evaluated": 1,\
"evaluates": 1,\
"evaluating": 1,\
"evaluation": 1,\
"evaluations": 1,\
"evaluative": 1,\
"eventual": 1,\
"eventuality": 1,\
"eventually": 1,\
"evidence": 1,\
"evidenced": 1,\
"evident": 1,\
"evidential": 1,\
"evidently": 1,\
"evolution": 1,\
"evolutionary": 1,\
"evolutionist": 1,\
"evolutionists": 1,\
"evolve": 1,\
"evolved": 1,\
"evolves": 1,\
"evolving": 1,\
"exceed": 1,\
"exceeded": 1,\
"exceeding": 1,\
"exceeds": 1,\
"exclude": 1,\
"excluded": 1,\
"excludes": 1,\
"excluding": 1,\
"exclusion": 1,\
"exclusionary": 1,\
"exclusionist": 1,\
"exclusions": 1,\
"exclusive": 1,\
"exclusively": 1,\
"exhibit": 1,\
"exhibited": 1,\
"exhibiting": 1,\
"exhibition": 1,\
"exhibitions": 1,\
"exhibits": 1,\
"expand": 1,\
"expanded": 1,\
"expanding": 1,\
"expands": 1,\
"expansion": 1,\
"expansionism": 1,\
"expansive": 1,\
"expert": 1,\
"expertise": 1,\
"expertly": 1,\
"experts": 1,\
"explicit": 1,\
"explicitly": 1,\
"exploit": 1,\
"exploitation": 1,\
"exploited": 1,\
"exploiting": 1,\
"exploits": 1,\
"export": 1,\
"exported": 1,\
"exporter": 1,\
"exporters": 1,\
"exporting": 1,\
"exports": 1,\
"expose": 1,\
"exposed": 1,\
"exposes": 1,\
"exposing": 1,\
"exposure": 1,\
"exposures": 1,\
"external": 1,\
"externalisation": 1,\
"externalise": 1,\
"externalised": 1,\
"externalises": 1,\
"externalising": 1,\
"externality": 1,\
"externalization": 1,\
"externalize": 1,\
"externalized": 1,\
"externalizes": 1,\
"externalizing": 1,\
"externally": 1,\
"extract": 1,\
"extracted": 1,\
"extracting": 1,\
"extraction": 1,\
"extracts": 1,\
"facilitate": 1,\
"facilitated": 1,\
"facilitates": 1,\
"facilitating": 1,\
"facilitation": 1,\
"facilitator": 1,\
"facilitators": 1,\
"facilities": 1,\
"facility": 1,\
"factor": 1,\
"factored": 1,\
"factoring": 1,\
"factors": 1,\
"feature": 1,\
"featured": 1,\
"features": 1,\
"featuring": 1,\
"federal": 1,\
"federation": 1,\
"federations": 1,\
"fee": 1,\
"fees": 1,\
"file": 1,\
"filed": 1,\
"files": 1,\
"filing": 1,\
"final": 1,\
"finalise": 1,\
"finalised": 1,\
"finalises": 1,\
"finalising": 1,\
"finality": 1,\
"finalize": 1,\
"finalized": 1,\
"finalizes": 1,\
"finalizing": 1,\
"finally": 1,\
"finals": 1,\
"finance": 1,\
"financed": 1,\
"finances": 1,\
"financial": 1,\
"financially": 1,\
"financier": 1,\
"financiers": 1,\
"financing": 1,\
"finite": 1,\
"flexibility": 1,\
"flexible": 1,\
"fluctuate": 1,\
"fluctuated": 1,\
"fluctuates": 1,\
"fluctuating": 1,\
"fluctuation": 1,\
"fluctuations": 1,\
"focus": 1,\
"focused": 1,\
"focuses": 1,\
"focusing": 1,\
"focussed": 1,\
"focussing": 1,\
"format": 1,\
"formats": 1,\
"formatted": 1,\
"formatting": 1,\
"formula": 1,\
"formulae": 1,\
"formulas": 1,\
"formulate": 1,\
"formulated": 1,\
"formulating": 1,\
"formulation": 1,\
"formulations": 1,\
"forthcoming": 1,\
"found": 1,\
"foundation": 1,\
"foundations": 1,\
"founded": 1,\
"founder": 1,\
"founders": 1,\
"founding": 1,\
"framework": 1,\
"frameworks": 1,\
"function": 1,\
"functional": 1,\
"functionally": 1,\
"functioned": 1,\
"functioning": 1,\
"functions": 1,\
"fund": 1,\
"fundamental": 1,\
"fundamentally": 1,\
"funded": 1,\
"funder": 1,\
"funders": 1,\
"funding": 1,\
"funds": 1,\
"furthermore": 1,\
"gender": 1,\
"genders": 1,\
"generate": 1,\
"generated": 1,\
"generates": 1,\
"generating": 1,\
"generation": 1,\
"generations": 1,\
"global": 1,\
"globalisation": 1,\
"globalization": 1,\
"globally": 1,\
"globe": 1,\
"goal": 1,\
"goals": 1,\
"grade": 1,\
"graded": 1,\
"grades": 1,\
"grading": 1,\
"grant": 1,\
"granted": 1,\
"granting": 1,\
"grants": 1,\
"guarantee": 1,\
"guaranteed": 1,\
"guaranteeing": 1,\
"guarantees": 1,\
"guideline": 1,\
"guidelines": 1,\
"hence": 1,\
"hierarchical": 1,\
"hierarchies": 1,\
"hierarchy": 1,\
"highlight": 1,\
"highlighted": 1,\
"highlighting": 1,\
"highlights": 1,\
"hypotheses": 1,\
"hypothesis": 1,\
"hypothesise": 1,\
"hypothesised": 1,\
"hypothesises": 1,\
"hypothesising": 1,\
"hypothesize": 1,\
"hypothesized": 1,\
"hypothesizes": 1,\
"hypothesizing": 1,\
"hypothetical": 1,\
"hypothetically": 1,\
"identical": 1,\
"identically": 1,\
"identifiable": 1,\
"identification": 1,\
"identified": 1,\
"identifies": 1,\
"identify": 1,\
"identifying": 1,\
"identities": 1,\
"identity": 1,\
"ideological": 1,\
"ideologically": 1,\
"ideologies": 1,\
"ideology": 1,\
"ignorance": 1,\
"ignorant": 1,\
"ignore": 1,\
"ignored": 1,\
"ignores": 1,\
"ignoring": 1,\
"illegal": 1,\
"illegality": 1,\
"illegally": 1,\
"illogical": 1,\
"illogically": 1,\
"illustrate": 1,\
"illustrated": 1,\
"illustrates": 1,\
"illustrating": 1,\
"illustration": 1,\
"illustrations": 1,\
"illustrative": 1,\
"image": 1,\
"imagery": 1,\
"images": 1,\
"immature": 1,\
"immaturity": 1,\
"immigrant": 1,\
"immigrants": 1,\
"immigrate": 1,\
"immigrated": 1,\
"immigrates": 1,\
"immigrating": 1,\
"immigration": 1,\
"impact": 1,\
"impacted": 1,\
"impacting": 1,\
"impacts": 1,\
"implement": 1,\
"implementation": 1,\
"implemented": 1,\
"implementing": 1,\
"implements": 1,\
"implicate": 1,\
"implicated": 1,\
"implicates": 1,\
"implicating": 1,\
"implication": 1,\
"implications": 1,\
"implicit": 1,\
"implicitly": 1,\
"implied": 1,\
"implies": 1,\
"imply": 1,\
"implying": 1,\
"impose": 1,\
"imposed": 1,\
"imposes": 1,\
"imposing": 1,\
"imposition": 1,\
"imprecise": 1,\
"inaccessible": 1,\
"inaccuracies": 1,\
"inaccuracy": 1,\
"inaccurate": 1,\
"inadequacies": 1,\
"inadequacy": 1,\
"inadequate": 1,\
"inadequately": 1,\
"inappropriacy": 1,\
"inappropriate": 1,\
"inappropriately": 1,\
"incapable": 1,\
"incapacitate": 1,\
"incapacitated": 1,\
"incentive": 1,\
"incentives": 1,\
"incidence": 1,\
"incident": 1,\
"incidentally": 1,\
"incidents": 1,\
"inclination": 1,\
"inclinations": 1,\
"incline": 1,\
"inclined": 1,\
"inclines": 1,\
"inclining": 1,\
"incoherent": 1,\
"incoherently": 1,\
"income": 1,\
"incomes": 1,\
"incompatibility": 1,\
"incompatible": 1,\
"inconceivable": 1,\
"inconceivably": 1,\
"inconclusive": 1,\
"inconclusively": 1,\
"inconsistencies": 1,\
"inconsistency": 1,\
"inconsistent": 1,\
"inconstancy": 1,\
"inconstantly": 1,\
"incorporate": 1,\
"incorporated": 1,\
"incorporates": 1,\
"incorporating": 1,\
"incorporation": 1,\
"indefinite": 1,\
"indefinitely": 1,\
"index": 1,\
"indexed": 1,\
"indexes": 1,\
"indexing": 1,\
"indicate": 1,\
"indicated": 1,\
"indicates": 1,\
"indicating": 1,\
"indication": 1,\
"indications": 1,\
"indicative": 1,\
"indicator": 1,\
"indicators": 1,\
"indiscrete": 1,\
"indiscretion": 1,\
"indistinct": 1,\
"indistinctly": 1,\
"individual": 1,\
"individualised": 1,\
"individualism": 1,\
"individualist": 1,\
"individualistic": 1,\
"individualists": 1,\
"individuality": 1,\
"individually": 1,\
"individuals": 1,\
"induce": 1,\
"induced": 1,\
"induces": 1,\
"inducing": 1,\
"induction": 1,\
"inevitability": 1,\
"inevitable": 1,\
"inevitably": 1,\
"infer": 1,\
"inference": 1,\
"inferences": 1,\
"inferred": 1,\
"inferring": 1,\
"infers": 1,\
"infinite": 1,\
"infinitely": 1,\
"inflexibility": 1,\
"inflexible": 1,\
"infrastructure": 1,\
"infrastructures": 1,\
"inherent": 1,\
"inherently": 1,\
"inhibit": 1,\
"inhibited": 1,\
"inhibiting": 1,\
"inhibition": 1,\
"inhibitions": 1,\
"inhibits": 1,\
"initial": 1,\
"initially": 1,\
"initiate": 1,\
"initiated": 1,\
"initiates": 1,\
"initiating": 1,\
"initiation": 1,\
"initiations": 1,\
"initiative": 1,\
"initiatives": 1,\
"initiator": 1,\
"initiators": 1,\
"injure": 1,\
"injured": 1,\
"injures": 1,\
"injuries": 1,\
"injuring": 1,\
"injury": 1,\
"innovate": 1,\
"innovated": 1,\
"innovates": 1,\
"innovating": 1,\
"innovation": 1,\
"innovations": 1,\
"innovative": 1,\
"innovator": 1,\
"innovators": 1,\
"input": 1,\
"inputs": 1,\
"insecure": 1,\
"insecurities": 1,\
"insecurity": 1,\
"insert": 1,\
"inserted": 1,\
"inserting": 1,\
"insertion": 1,\
"inserts": 1,\
"insight": 1,\
"insightful": 1,\
"insights": 1,\
"insignificant": 1,\
"insignificantly": 1,\
"inspect": 1,\
"inspected": 1,\
"inspecting": 1,\
"inspection": 1,\
"inspections": 1,\
"inspector": 1,\
"inspectors": 1,\
"inspects": 1,\
"instability": 1,\
"instance": 1,\
"instances": 1,\
"institute": 1,\
"instituted": 1,\
"institutes": 1,\
"instituting": 1,\
"institution": 1,\
"institutional": 1,\
"institutionalise": 1,\
"institutionalised": 1,\
"institutionalises": 1,\
"institutionalising": 1,\
"institutionalized": 1,\
"institutionalizes": 1,\
"institutionalizing": 1,\
"institutionally": 1,\
"institutions": 1,\
"instruct": 1,\
"instructed": 1,\
"instructing": 1,\
"instruction": 1,\
"instructions": 1,\
"instructive": 1,\
"instructor": 1,\
"instructors": 1,\
"instructs": 1,\
"insufficient": 1,\
"insufficiently": 1,\
"integral": 1,\
"integrate": 1,\
"integrated": 1,\
"integrates": 1,\
"integrating": 1,\
"integration": 1,\
"integrity": 1,\
"intelligence": 1,\
"intelligent": 1,\
"intelligently": 1,\
"intense": 1,\
"intensely": 1,\
"intenseness": 1,\
"intensification": 1,\
"intensified": 1,\
"intensifies": 1,\
"intensify": 1,\
"intensifying": 1,\
"intension": 1,\
"intensity": 1,\
"intensive": 1,\
"intensively": 1,\
"interact": 1,\
"interacted": 1,\
"interacting": 1,\
"interaction": 1,\
"interactions": 1,\
"interactive": 1,\
"interactively": 1,\
"interacts": 1,\
"intermediate": 1,\
"internal": 1,\
"internalise": 1,\
"internalised": 1,\
"internalises": 1,\
"internalising": 1,\
"internalize": 1,\
"internalized": 1,\
"internalizes": 1,\
"internalizing": 1,\
"internally": 1,\
"interpret": 1,\
"interpretation": 1,\
"interpretations": 1,\
"interpretative": 1,\
"interpreted": 1,\
"interpreting": 1,\
"interpretive": 1,\
"interprets": 1,\
"interval": 1,\
"intervals": 1,\
"intervene": 1,\
"intervened": 1,\
"intervenes": 1,\
"intervening": 1,\
"intervention": 1,\
"interventions": 1,\
"intrinsic": 1,\
"intrinsically": 1,\
"invalidate": 1,\
"invalidity": 1,\
"invariable": 1,\
"invariably": 1,\
"invest": 1,\
"invested": 1,\
"investigate": 1,\
"investigated": 1,\
"investigates": 1,\
"investigating": 1,\
"investigation": 1,\
"investigations": 1,\
"investigative": 1,\
"investigator": 1,\
"investigators": 1,\
"investing": 1,\
"investment": 1,\
"investments": 1,\
"investor": 1,\
"investors": 1,\
"invests": 1,\
"invisibility": 1,\
"invisible": 1,\
"invoke": 1,\
"invoked": 1,\
"invokes": 1,\
"invoking": 1,\
"involve": 1,\
"involved": 1,\
"involvement": 1,\
"involves": 1,\
"involving": 1,\
"irrational": 1,\
"irrelevance": 1,\
"irrelevant": 1,\
"irreversible": 1,\
"isolate": 1,\
"isolated": 1,\
"isolates": 1,\
"isolating": 1,\
"isolation": 1,\
"isolationism": 1,\
"issue": 1,\
"issued": 1,\
"issues": 1,\
"issuing": 1,\
"item": 1,\
"itemisation": 1,\
"itemise": 1,\
"itemised": 1,\
"itemises": 1,\
"itemising": 1,\
"items": 1,\
"job": 1,\
"jobs": 1,\
"journal": 1,\
"journals": 1,\
"justifiable": 1,\
"justifiably": 1,\
"justification": 1,\
"justifications": 1,\
"justified": 1,\
"justifies": 1,\
"justify": 1,\
"justifying": 1,\
"label": 1,\
"labeled": 1,\
"labeling": 1,\
"labelled": 1,\
"labelling": 1,\
"labels": 1,\
"labor": 1,\
"labored": 1,\
"labors": 1,\
"labour": 1,\
"laboured": 1,\
"labouring": 1,\
"labours": 1,\
"layer": 1,\
"layered": 1,\
"layering": 1,\
"layers": 1,\
"lecture": 1,\
"lectured": 1,\
"lecturer": 1,\
"lecturers": 1,\
"lectures": 1,\
"lecturing": 1,\
"legal": 1,\
"legality": 1,\
"legally": 1,\
"legislate": 1,\
"legislated": 1,\
"legislates": 1,\
"legislating": 1,\
"legislation": 1,\
"legislative": 1,\
"legislator": 1,\
"legislators": 1,\
"legislature": 1,\
"levies": 1,\
"levy": 1,\
"liberal": 1,\
"liberalisation": 1,\
"liberalise": 1,\
"liberalised": 1,\
"liberalises": 1,\
"liberalising": 1,\
"liberalism": 1,\
"liberalization": 1,\
"liberalize": 1,\
"liberalized": 1,\
"liberalizes": 1,\
"liberalizing": 1,\
"liberally": 1,\
"liberals": 1,\
"liberate": 1,\
"liberated": 1,\
"liberates": 1,\
"liberating": 1,\
"liberation": 1,\
"liberations": 1,\
"liberator": 1,\
"liberators": 1,\
"licence": 1,\
"licences": 1,\
"license": 1,\
"licensed": 1,\
"licenses": 1,\
"licensing": 1,\
"likewise": 1,\
"link": 1,\
"linkage": 1,\
"linkages": 1,\
"linked": 1,\
"linking": 1,\
"links": 1,\
"locate": 1,\
"located": 1,\
"locating": 1,\
"location": 1,\
"locations": 1,\
"logic": 1,\
"logical": 1,\
"logically": 1,\
"logician": 1,\
"logicians": 1,\
"maintain": 1,\
"maintained": 1,\
"maintaining": 1,\
"maintains": 1,\
"maintenance": 1,\
"major": 1,\
"majorities": 1,\
"majority": 1,\
"manipulate": 1,\
"manipulated": 1,\
"manipulates": 1,\
"manipulating": 1,\
"manipulation": 1,\
"manipulations": 1,\
"manipulative": 1,\
"manual": 1,\
"manually": 1,\
"manuals": 1,\
"margin": 1,\
"marginal": 1,\
"marginally": 1,\
"margins": 1,\
"maturation": 1,\
"maturational": 1,\
"mature": 1,\
"matured": 1,\
"matures": 1,\
"maturing": 1,\
"maturity": 1,\
"max": 1,\
"maximisation": 1,\
"maximise": 1,\
"maximised": 1,\
"maximises": 1,\
"maximising": 1,\
"maximization": 1,\
"maximize": 1,\
"maximized": 1,\
"maximizes": 1,\
"maximizing": 1,\
"maximum": 1,\
"mechanism": 1,\
"mechanisms": 1,\
"media": 1,\
"mediate": 1,\
"mediated": 1,\
"mediates": 1,\
"mediating": 1,\
"mediation": 1,\
"medical": 1,\
"medically": 1,\
"medium": 1,\
"mental": 1,\
"mentality": 1,\
"mentally": 1,\
"method": 1,\
"methodical": 1,\
"methodological": 1,\
"methodologies": 1,\
"methodology": 1,\
"methods": 1,\
"migrant": 1,\
"migrants": 1,\
"migrate": 1,\
"migrated": 1,\
"migrates": 1,\
"migrating": 1,\
"migration": 1,\
"migrations": 1,\
"migratory": 1,\
"military": 1,\
"minimal": 1,\
"minimalisation": 1,\
"minimalise": 1,\
"minimalised": 1,\
"minimalises": 1,\
"minimalising": 1,\
"minimalist": 1,\
"minimalistic": 1,\
"minimalists": 1,\
"minimalization": 1,\
"minimalize": 1,\
"minimalized": 1,\
"minimalizes": 1,\
"minimalizing": 1,\
"minimally": 1,\
"minimise": 1,\
"minimised": 1,\
"minimises": 1,\
"minimising": 1,\
"minimize": 1,\
"minimized": 1,\
"minimizes": 1,\
"minimizing": 1,\
"minimum": 1,\
"ministered": 1,\
"ministerial": 1,\
"ministering": 1,\
"ministries": 1,\
"ministry": 1,\
"minor": 1,\
"minorities": 1,\
"minority": 1,\
"minors": 1,\
"misinterpret": 1,\
"misinterpretation": 1,\
"misinterpretations": 1,\
"misinterpreted": 1,\
"misinterpreting": 1,\
"misinterprets": 1,\
"mode": 1,\
"modes": 1,\
"modification": 1,\
"modifications": 1,\
"modified": 1,\
"modifies": 1,\
"modify": 1,\
"modifying": 1,\
"monitor": 1,\
"monitored": 1,\
"monitoring": 1,\
"monitors": 1,\
"motivate": 1,\
"motivated": 1,\
"motivates": 1,\
"motivating": 1,\
"motivation": 1,\
"motivations": 1,\
"motive": 1,\
"motives": 1,\
"multidimensional": 1,\
"mutual": 1,\
"mutually": 1,\
"negate": 1,\
"negated": 1,\
"negates": 1,\
"negating": 1,\
"negative": 1,\
"negatively": 1,\
"negatives": 1,\
"network": 1,\
"networked": 1,\
"networking": 1,\
"networks": 1,\
"neutral": 1,\
"neutralisation": 1,\
"neutralise": 1,\
"neutralised": 1,\
"neutralises": 1,\
"neutralising": 1,\
"neutrality": 1,\
"neutralization": 1,\
"neutralize": 1,\
"neutralized": 1,\
"neutralizes": 1,\
"neutralizing": 1,\
"nevertheless": 1,\
"non-conformist": 1,\
"non-conformists": 1,\
"non-conformity": 1,\
"nonconformist": 1,\
"nonconformists": 1,\
"nonconformity": 1,\
"nonetheless": 1,\
"non‑traditional": 1,\
"norm": 1,\
"normal": 1,\
"normalisation": 1,\
"normalise": 1,\
"normalised": 1,\
"normalises": 1,\
"normalising": 1,\
"normality": 1,\
"normalization": 1,\
"normalize": 1,\
"normalized": 1,\
"normalizes": 1,\
"normalizing": 1,\
"normally": 1,\
"norms": 1,\
"notion": 1,\
"notions": 1,\
"notwithstanding": 1,\
"nuclear": 1,\
"objective": 1,\
"objectively": 1,\
"objectivity": 1,\
"obtain": 1,\
"obtainable": 1,\
"obtained": 1,\
"obtaining": 1,\
"obtains": 1,\
"obvious": 1,\
"obviously": 1,\
"occupancy": 1,\
"occupant": 1,\
"occupants": 1,\
"occupation": 1,\
"occupational": 1,\
"occupations": 1,\
"occupied": 1,\
"occupier": 1,\
"occupiers": 1,\
"occupies": 1,\
"occupy": 1,\
"occupying": 1,\
"occur": 1,\
"occurred": 1,\
"occurrence": 1,\
"occurrences": 1,\
"occurring": 1,\
"occurs": 1,\
"odd": 1,\
"odds": 1,\
"offset": 1,\
"offsets": 1,\
"offsetting": 1,\
"ongoing": 1,\
"option": 1,\
"optional": 1,\
"options": 1,\
"orient": 1,\
"orientate": 1,\
"orientated": 1,\
"orientates": 1,\
"orientating": 1,\
"orientation": 1,\
"oriented": 1,\
"orienting": 1,\
"orients": 1,\
"outcome": 1,\
"outcomes": 1,\
"output": 1,\
"outputs": 1,\
"overall": 1,\
"overestimate": 1,\
"overestimated": 1,\
"overestimates": 1,\
"overestimating": 1,\
"overlap": 1,\
"overlapped": 1,\
"overlapping": 1,\
"overlaps": 1,\
"overseas": 1,\
"over‑estimate": 1,\
"panel": 1,\
"panelled": 1,\
"panelling": 1,\
"panels": 1,\
"paradigm": 1,\
"paradigms": 1,\
"paragraph": 1,\
"paragraphing": 1,\
"paragraphs": 1,\
"parallel": 1,\
"paralleled": 1,\
"parallelled": 1,\
"parallelling": 1,\
"parallels": 1,\
"parameter": 1,\
"parameters": 1,\
"participant": 1,\
"participants": 1,\
"participate": 1,\
"participated": 1,\
"participates": 1,\
"participating": 1,\
"participation": 1,\
"participatory": 1,\
"partner": 1,\
"partners": 1,\
"partnership": 1,\
"partnerships": 1,\
"passive": 1,\
"passively": 1,\
"passivity": 1,\
"perceive": 1,\
"perceived": 1,\
"perceives": 1,\
"perceiving": 1,\
"percent": 1,\
"percentage": 1,\
"percentages": 1,\
"perception": 1,\
"perceptions": 1,\
"period": 1,\
"periodic": 1,\
"periodical": 1,\
"periodically": 1,\
"periodicals": 1,\
"periods": 1,\
"persist": 1,\
"persisted": 1,\
"persistence": 1,\
"persistent": 1,\
"persistently": 1,\
"persisting": 1,\
"persists": 1,\
"perspective": 1,\
"perspectives": 1,\
"phase": 1,\
"phased": 1,\
"phases": 1,\
"phasing": 1,\
"phenomena": 1,\
"phenomenal": 1,\
"phenomenon": 1,\
"philosopher": 1,\
"philosophers": 1,\
"philosophical": 1,\
"philosophically": 1,\
"philosophies": 1,\
"philosophise": 1,\
"philosophised": 1,\
"philosophises": 1,\
"philosophising": 1,\
"philosophize": 1,\
"philosophized": 1,\
"philosophizes": 1,\
"philosophizing": 1,\
"philosophy": 1,\
"physical": 1,\
"physically": 1,\
"plus": 1,\
"pluses": 1,\
"policies": 1,\
"policy": 1,\
"portion": 1,\
"portions": 1,\
"pose": 1,\
"posed": 1,\
"poses": 1,\
"posing": 1,\
"positive": 1,\
"positively": 1,\
"potential": 1,\
"potentially": 1,\
"practitioner": 1,\
"practitioners": 1,\
"precede": 1,\
"preceded": 1,\
"precedence": 1,\
"precedent": 1,\
"precedes": 1,\
"preceding": 1,\
"precise": 1,\
"precisely": 1,\
"precision": 1,\
"predict": 1,\
"predictability": 1,\
"predictable": 1,\
"predictably": 1,\
"predicted": 1,\
"predicting": 1,\
"prediction": 1,\
"predictions": 1,\
"predicts": 1,\
"predominance": 1,\
"predominant": 1,\
"predominantly": 1,\
"predominate": 1,\
"predominated": 1,\
"predominates": 1,\
"predominating": 1,\
"preliminaries": 1,\
"preliminary": 1,\
"presumably": 1,\
"presume": 1,\
"presumed": 1,\
"presumes": 1,\
"presuming": 1,\
"presumption": 1,\
"presumptions": 1,\
"presumptuous": 1,\
"previous": 1,\
"previously": 1,\
"primacy": 1,\
"primarily": 1,\
"primary": 1,\
"prime": 1,\
"principal": 1,\
"principally": 1,\
"principle": 1,\
"principled": 1,\
"principles": 1,\
"prior": 1,\
"priorities": 1,\
"prioritisation": 1,\
"prioritise": 1,\
"prioritised": 1,\
"prioritises": 1,\
"prioritising": 1,\
"prioritization": 1,\
"prioritize": 1,\
"prioritized": 1,\
"prioritizes": 1,\
"prioritizing": 1,\
"priority": 1,\
"procedural": 1,\
"procedure": 1,\
"procedures": 1,\
"proceed": 1,\
"proceeded": 1,\
"proceeding": 1,\
"proceedings": 1,\
"proceeds": 1,\
"process": 1,\
"processed": 1,\
"processes": 1,\
"processing": 1,\
"professional": 1,\
"professionalism": 1,\
"professionally": 1,\
"professionals": 1,\
"prohibit": 1,\
"prohibited": 1,\
"prohibiting": 1,\
"prohibition": 1,\
"prohibitions": 1,\
"prohibitive": 1,\
"prohibits": 1,\
"project": 1,\
"projected": 1,\
"projecting": 1,\
"projection": 1,\
"projections": 1,\
"projects": 1,\
"promote": 1,\
"promoted": 1,\
"promoter": 1,\
"promoters": 1,\
"promotes": 1,\
"promoting": 1,\
"promotion": 1,\
"promotions": 1,\
"proportion": 1,\
"proportional": 1,\
"proportionally": 1,\
"proportionate": 1,\
"proportionately": 1,\
"proportions": 1,\
"prospect": 1,\
"prospective": 1,\
"prospects": 1,\
"protocol": 1,\
"protocols": 1,\
"psychological": 1,\
"psychologically": 1,\
"psychologist": 1,\
"psychologists": 1,\
"psychology": 1,\
"publication": 1,\
"publications": 1,\
"publish": 1,\
"published": 1,\
"publisher": 1,\
"publishers": 1,\
"publishes": 1,\
"publishing": 1,\
"purchase": 1,\
"purchased": 1,\
"purchaser": 1,\
"purchasers": 1,\
"purchases": 1,\
"purchasing": 1,\
"pursue": 1,\
"pursued": 1,\
"pursues": 1,\
"pursuing": 1,\
"pursuit": 1,\
"pursuits": 1,\
"qualitative": 1,\
"qualitatively": 1,\
"quotation": 1,\
"quotations": 1,\
"quote": 1,\
"quoted": 1,\
"quotes": 1,\
"quoting": 1,\
"radical": 1,\
"radically": 1,\
"radicals": 1,\
"random": 1,\
"randomly": 1,\
"randomness": 1,\
"range": 1,\
"ranged": 1,\
"ranges": 1,\
"ranging": 1,\
"ratio": 1,\
"rational": 1,\
"rationalisation": 1,\
"rationalisations": 1,\
"rationalise": 1,\
"rationalised": 1,\
"rationalises": 1,\
"rationalising": 1,\
"rationalism": 1,\
"rationality": 1,\
"rationalization": 1,\
"rationalizations": 1,\
"rationalize": 1,\
"rationalized": 1,\
"rationalizes": 1,\
"rationally": 1,\
"ratios": 1,\
"re-evaluate": 1,\
"re-evaluated": 1,\
"re-evaluates": 1,\
"re-evaluating": 1,\
"re-evaluation": 1,\
"react": 1,\
"reacted": 1,\
"reacting": 1,\
"reaction": 1,\
"reactionaries": 1,\
"reactionary": 1,\
"reactions": 1,\
"reactivate": 1,\
"reactivation": 1,\
"reactive": 1,\
"reactor": 1,\
"reactors": 1,\
"reacts": 1,\
"readjust": 1,\
"readjusted": 1,\
"readjusting": 1,\
"readjustment": 1,\
"readjustments": 1,\
"readjusts": 1,\
"reassess": 1,\
"reassessed": 1,\
"reassessing": 1,\
"reassessment": 1,\
"reassign": 1,\
"reassigned": 1,\
"reassigning": 1,\
"reassigns": 1,\
"recommenced": 1,\
"recommences": 1,\
"recommencing": 1,\
"reconstruct": 1,\
"reconstructed": 1,\
"reconstructing": 1,\
"reconstruction": 1,\
"reconstructs": 1,\
"recover": 1,\
"recoverable": 1,\
"recovered": 1,\
"recovering": 1,\
"recovers": 1,\
"recovery": 1,\
"recreate": 1,\
"recreated": 1,\
"recreates": 1,\
"recreating": 1,\
"redefine": 1,\
"redefined": 1,\
"redefines": 1,\
"redefining": 1,\
"redistribute": 1,\
"redistributed": 1,\
"redistributes": 1,\
"redistributing": 1,\
"redistribution": 1,\
"redraft": 1,\
"redrafted": 1,\
"redrafting": 1,\
"redrafts": 1,\
"refine": 1,\
"refined": 1,\
"refinement": 1,\
"refinements": 1,\
"refines": 1,\
"refining": 1,\
"refocus": 1,\
"refocused": 1,\
"refocuses": 1,\
"refocusing": 1,\
"refocussed": 1,\
"refocusses": 1,\
"refocussing": 1,\
"reformulate": 1,\
"reformulated": 1,\
"reformulating": 1,\
"reformulation": 1,\
"reformulations": 1,\
"regime": 1,\
"regimes": 1,\
"region": 1,\
"regional": 1,\
"regionally": 1,\
"regions": 1,\
"register": 1,\
"registered": 1,\
"registering": 1,\
"registers": 1,\
"registration": 1,\
"regulate": 1,\
"regulated": 1,\
"regulates": 1,\
"regulating": 1,\
"regulation": 1,\
"regulations": 1,\
"regulator": 1,\
"regulators": 1,\
"regulatory": 1,\
"reinforce": 1,\
"reinforced": 1,\
"reinforcement": 1,\
"reinforcements": 1,\
"reinforces": 1,\
"reinforcing": 1,\
"reinterpret": 1,\
"reinterpretation": 1,\
"reinterpretations": 1,\
"reinterpreted": 1,\
"reinterpreting": 1,\
"reinterprets": 1,\
"reinvest": 1,\
"reinvested": 1,\
"reinvesting": 1,\
"reinvestment": 1,\
"reinvests": 1,\
"reject": 1,\
"rejected": 1,\
"rejecting": 1,\
"rejection": 1,\
"rejections": 1,\
"rejects": 1,\
"relax": 1,\
"relaxation": 1,\
"relaxed": 1,\
"relaxes": 1,\
"relaxing": 1,\
"release": 1,\
"released": 1,\
"releases": 1,\
"releasing": 1,\
"relevance": 1,\
"relevant": 1,\
"reliability": 1,\
"reliable": 1,\
"reliably": 1,\
"reliance": 1,\
"reliant": 1,\
"relied": 1,\
"relies": 1,\
"relocate": 1,\
"relocated": 1,\
"relocates": 1,\
"relocating": 1,\
"relocation": 1,\
"reluctance": 1,\
"reluctant": 1,\
"reluctantly": 1,\
"rely": 1,\
"relying": 1,\
"removable": 1,\
"removal": 1,\
"removals": 1,\
"remove": 1,\
"removed": 1,\
"removes": 1,\
"removing": 1,\
"reoccur": 1,\
"reoccurred": 1,\
"reoccurring": 1,\
"reoccurs": 1,\
"reorient": 1,\
"reorientation": 1,\
"require": 1,\
"required": 1,\
"requirement": 1,\
"requirements": 1,\
"requires": 1,\
"requiring": 1,\
"reschedule": 1,\
"rescheduled": 1,\
"reschedules": 1,\
"rescheduling": 1,\
"research": 1,\
"researched": 1,\
"researcher": 1,\
"researchers": 1,\
"researches": 1,\
"researching": 1,\
"reside": 1,\
"resided": 1,\
"residence": 1,\
"resident": 1,\
"residential": 1,\
"residents": 1,\
"resides": 1,\
"residing": 1,\
"resolution": 1,\
"resolve": 1,\
"resolved": 1,\
"resolves": 1,\
"resolving": 1,\
"resource": 1,\
"resourced": 1,\
"resourceful": 1,\
"resources": 1,\
"resourcing": 1,\
"respond": 1,\
"responded": 1,\
"respondent": 1,\
"respondents": 1,\
"responding": 1,\
"responds": 1,\
"response": 1,\
"responses": 1,\
"responsive": 1,\
"responsiveness": 1,\
"restoration": 1,\
"restore": 1,\
"restored": 1,\
"restores": 1,\
"restoring": 1,\
"restrain": 1,\
"restrained": 1,\
"restraining": 1,\
"restrains": 1,\
"restraint": 1,\
"restraints": 1,\
"restrict": 1,\
"restricted": 1,\
"restricting": 1,\
"restriction": 1,\
"restrictions": 1,\
"restrictive": 1,\
"restrictively": 1,\
"restricts": 1,\
"restructure": 1,\
"restructured": 1,\
"restructures": 1,\
"restructuring": 1,\
"retain": 1,\
"retained": 1,\
"retainer": 1,\
"retainers": 1,\
"retaining": 1,\
"retains": 1,\
"retention": 1,\
"retentive": 1,\
"reveal": 1,\
"revealed": 1,\
"revealing": 1,\
"reveals": 1,\
"revelation": 1,\
"revelations": 1,\
"revenue": 1,\
"revenues": 1,\
"reversal": 1,\
"reversals": 1,\
"reverse": 1,\
"reversed": 1,\
"reverses": 1,\
"reversible": 1,\
"reversing": 1,\
"revise": 1,\
"revised": 1,\
"revises": 1,\
"revising": 1,\
"revision": 1,\
"revisions": 1,\
"revolution": 1,\
"revolutionaries": 1,\
"revolutionary": 1,\
"revolutionise": 1,\
"revolutionised": 1,\
"revolutionises": 1,\
"revolutionising": 1,\
"revolutionist": 1,\
"revolutionists": 1,\
"revolutionize": 1,\
"revolutionized": 1,\
"revolutionizes": 1,\
"revolutionizing": 1,\
"revolutions": 1,\
"rigid": 1,\
"rigidities": 1,\
"rigidity": 1,\
"rigidly": 1,\
"role": 1,\
"roles": 1,\
"route": 1,\
"routed": 1,\
"routes": 1,\
"routing": 1,\
"scenario": 1,\
"scenarios": 1,\
"schedule": 1,\
"scheduled": 1,\
"schedules": 1,\
"scheduling": 1,\
"schematic": 1,\
"schematically": 1,\
"scheme": 1,\
"schemed": 1,\
"schemes": 1,\
"scheming": 1,\
"scope": 1,\
"section": 1,\
"sectioned": 1,\
"sectioning": 1,\
"sections": 1,\
"sector": 1,\
"sectors": 1,\
"secure": 1,\
"secured": 1,\
"securely": 1,\
"secures": 1,\
"securing": 1,\
"securities": 1,\
"security": 1,\
"seek": 1,\
"seeking": 1,\
"seeks": 1,\
"select": 1,\
"selected": 1,\
"selecting": 1,\
"selection": 1,\
"selections": 1,\
"selective": 1,\
"selectively": 1,\
"selector": 1,\
"selectors": 1,\
"selects": 1,\
"sequence": 1,\
"sequenced": 1,\
"sequences": 1,\
"sequencing": 1,\
"sequential": 1,\
"sequentially": 1,\
"series": 1,\
"sex": 1,\
"sexes": 1,\
"sexism": 1,\
"sexual": 1,\
"sexuality": 1,\
"sexually": 1,\
"shift": 1,\
"shifted": 1,\
"shifting": 1,\
"shifts": 1,\
"significance": 1,\
"significant": 1,\
"significantly": 1,\
"signified": 1,\
"signifies": 1,\
"signify": 1,\
"signifying": 1,\
"similar": 1,\
"similarities": 1,\
"similarity": 1,\
"similarly": 1,\
"simulate": 1,\
"simulated": 1,\
"simulates": 1,\
"simulating": 1,\
"simulation": 1,\
"site": 1,\
"sites": 1,\
"sole": 1,\
"solely": 1,\
"somewhat": 1,\
"sought": 1,\
"source": 1,\
"sourced": 1,\
"sources": 1,\
"sourcing": 1,\
"so‑called": 1,\
"specifiable": 1,\
"specific": 1,\
"specifically": 1,\
"specification": 1,\
"specifications": 1,\
"specificity": 1,\
"specifics": 1,\
"specified": 1,\
"specifies": 1,\
"specify": 1,\
"specifying": 1,\
"sphere": 1,\
"spheres": 1,\
"spherical": 1,\
"spherically": 1,\
"stabilisation": 1,\
"stabilise": 1,\
"stabilised": 1,\
"stabilises": 1,\
"stabilising": 1,\
"stability": 1,\
"stabilization": 1,\
"stabilize": 1,\
"stabilized": 1,\
"stabilizes": 1,\
"stabilizing": 1,\
"stable": 1,\
"statistic": 1,\
"statistical": 1,\
"statistically": 1,\
"statistician": 1,\
"statisticians": 1,\
"statistics": 1,\
"status": 1,\
"straightforward": 1,\
"strategic": 1,\
"strategically": 1,\
"strategies": 1,\
"strategist": 1,\
"strategists": 1,\
"strategy": 1,\
"stress": 1,\
"stressed": 1,\
"stresses": 1,\
"stressful": 1,\
"stressing": 1,\
"structural": 1,\
"structurally": 1,\
"structure": 1,\
"structured": 1,\
"structures": 1,\
"structuring": 1,\
"style": 1,\
"styled": 1,\
"styles": 1,\
"styling": 1,\
"stylise": 1,\
"stylised": 1,\
"stylises": 1,\
"stylish": 1,\
"stylising": 1,\
"stylize": 1,\
"stylized": 1,\
"stylizes": 1,\
"stylizing": 1,\
"submission": 1,\
"submissions": 1,\
"submit": 1,\
"submits": 1,\
"submitted": 1,\
"submitting": 1,\
"subordinate": 1,\
"subordinates": 1,\
"subordination": 1,\
"subsequent": 1,\
"subsequently": 1,\
"subsidiary": 1,\
"subsidies": 1,\
"subsidise": 1,\
"subsidised": 1,\
"subsidises": 1,\
"subsidising": 1,\
"subsidize": 1,\
"subsidized": 1,\
"subsidizes": 1,\
"subsidizing": 1,\
"subsidy": 1,\
"substitute": 1,\
"substituted": 1,\
"substitutes": 1,\
"substituting": 1,\
"substitution": 1,\
"succession": 1,\
"successions": 1,\
"successive": 1,\
"successively": 1,\
"successor": 1,\
"successors": 1,\
"sufficiency": 1,\
"sufficient": 1,\
"sufficiently": 1,\
"sum": 1,\
"summaries": 1,\
"summarisation": 1,\
"summarisations": 1,\
"summarise": 1,\
"summarised": 1,\
"summarises": 1,\
"summarising": 1,\
"summarization": 1,\
"summarizations": 1,\
"summarize": 1,\
"summarized": 1,\
"summarizes": 1,\
"summarizing": 1,\
"summary": 1,\
"summation": 1,\
"summed": 1,\
"summing": 1,\
"sums": 1,\
"supplement": 1,\
"supplementary": 1,\
"supplemented": 1,\
"supplementing": 1,\
"supplements": 1,\
"survey": 1,\
"surveyed": 1,\
"surveying": 1,\
"surveys": 1,\
"survival": 1,\
"survive": 1,\
"survived": 1,\
"survives": 1,\
"surviving": 1,\
"survivor": 1,\
"survivors": 1,\
"suspend": 1,\
"suspended": 1,\
"suspending": 1,\
"suspends": 1,\
"suspension": 1,\
"sustain": 1,\
"sustainability": 1,\
"sustainable": 1,\
"sustained": 1,\
"sustaining": 1,\
"sustains": 1,\
"sustenance": 1,\
"symbol": 1,\
"symbolic": 1,\
"symbolically": 1,\
"symbolise": 1,\
"symbolised": 1,\
"symbolises": 1,\
"symbolising": 1,\
"symbolism": 1,\
"symbolize": 1,\
"symbolized": 1,\
"symbolizes": 1,\
"symbolizing": 1,\
"symbols": 1,\
"tape": 1,\
"taped": 1,\
"tapes": 1,\
"taping": 1,\
"target": 1,\
"targeted": 1,\
"targeting": 1,\
"targets": 1,\
"task": 1,\
"tasks": 1,\
"team": 1,\
"teamed": 1,\
"teaming": 1,\
"teams": 1,\
"technical": 1,\
"technically": 1,\
"technique": 1,\
"techniques": 1,\
"technological": 1,\
"technologically": 1,\
"technology": 1,\
"temporarily": 1,\
"temporary": 1,\
"tense": 1,\
"tensely": 1,\
"tenser": 1,\
"tensest": 1,\
"tension": 1,\
"tensions": 1,\
"terminal": 1,\
"terminals": 1,\
"terminate": 1,\
"terminated": 1,\
"terminates": 1,\
"terminating": 1,\
"termination": 1,\
"terminations": 1,\
"text": 1,\
"texts": 1,\
"textual": 1,\
"thematic": 1,\
"thematically": 1,\
"theme": 1,\
"themes": 1,\
"theoretical": 1,\
"theoretically": 1,\
"theories": 1,\
"theorist": 1,\
"theorists": 1,\
"theory": 1,\
"thereby": 1,\
"theses": 1,\
"thesis": 1,\
"topic": 1,\
"topical": 1,\
"topics": 1,\
"trace": 1,\
"traceable": 1,\
"traced": 1,\
"traces": 1,\
"tracing": 1,\
"tradition": 1,\
"traditional": 1,\
"traditionalist": 1,\
"traditionally": 1,\
"traditions": 1,\
"transfer": 1,\
"transferable": 1,\
"transference": 1,\
"transferred": 1,\
"transferring": 1,\
"transfers": 1,\
"transform": 1,\
"transformation": 1,\
"transformations": 1,\
"transformed": 1,\
"transforming": 1,\
"transforms": 1,\
"transit": 1,\
"transited": 1,\
"transiting": 1,\
"transition": 1,\
"transitional": 1,\
"transitions": 1,\
"transitory": 1,\
"transits": 1,\
"transmission": 1,\
"transmissions": 1,\
"transmit": 1,\
"transmits": 1,\
"transmitted": 1,\
"transmitting": 1,\
"transport": 1,\
"transportation": 1,\
"transported": 1,\
"transporter": 1,\
"transporters": 1,\
"transporting": 1,\
"transports": 1,\
"trend": 1,\
"trends": 1,\
"trigger": 1,\
"triggered": 1,\
"triggering": 1,\
"triggers": 1,\
"ultimate": 1,\
"ultimately": 1,\
"unaccompanied": 1,\
"unaffected": 1,\
"unaided": 1,\
"unalterable": 1,\
"unaltered": 1,\
"unambiguous": 1,\
"unambiguously": 1,\
"unanticipated": 1,\
"unappreciated": 1,\
"unapproachable": 1,\
"unassessed": 1,\
"unassigned": 1,\
"unassisted": 1,\
"unattached": 1,\
"unattainable": 1,\
"unavailable": 1,\
"unaware": 1,\
"unbiased": 1,\
"uncharted": 1,\
"uncommunicative": 1,\
"unconfined": 1,\
"unconstitutional": 1,\
"unconstrained": 1,\
"uncontextualised": 1,\
"uncontextualized": 1,\
"uncontroversial": 1,\
"unconventional": 1,\
"unconvinced": 1,\
"uncultured": 1,\
"undefined": 1,\
"undeniable": 1,\
"under-resourced": 1,\
"underestimate": 1,\
"underestimated": 1,\
"underestimates": 1,\
"underestimating": 1,\
"undergo": 1,\
"undergoes": 1,\
"undergoing": 1,\
"undergone": 1,\
"underlay": 1,\
"underlie": 1,\
"underlies": 1,\
"underlying": 1,\
"undertake": 1,\
"undertaken": 1,\
"undertakes": 1,\
"undertaking": 1,\
"undertook": 1,\
"underwent": 1,\
"undiminished": 1,\
"uneconomical": 1,\
"unethical": 1,\
"unfounded": 1,\
"unidentifiable": 1,\
"unification": 1,\
"unified": 1,\
"unifies": 1,\
"uniform": 1,\
"uniformity": 1,\
"uniformly": 1,\
"unify": 1,\
"unifying": 1,\
"uninjured": 1,\
"unintelligent": 1,\
"uninvolved": 1,\
"unique": 1,\
"uniquely": 1,\
"uniqueness": 1,\
"unjustified": 1,\
"unlicensed": 1,\
"unmodified": 1,\
"unmonitored": 1,\
"unmotivated": 1,\
"unobtainable": 1,\
"unparalleled": 1,\
"unprecedented": 1,\
"unpredictability": 1,\
"unpredictable": 1,\
"unprincipled": 1,\
"unpublished": 1,\
"unregulated": 1,\
"unreliable": 1,\
"unresolved": 1,\
"unresourceful": 1,\
"unresponsive": 1,\
"unrestrained": 1,\
"unrestricted": 1,\
"unrestrictive": 1,\
"unscheduled": 1,\
"unspecified": 1,\
"unstable": 1,\
"unstressed": 1,\
"unstructured": 1,\
"unsustainable": 1,\
"utilisation": 1,\
"utilise": 1,\
"utilised": 1,\
"utiliser": 1,\
"utilisers": 1,\
"utilises": 1,\
"utilising": 1,\
"utilities": 1,\
"utility": 1,\
"utilization": 1,\
"utilize": 1,\
"utilized": 1,\
"utilizes": 1,\
"utilizing": 1,\
"valid": 1,\
"validate": 1,\
"validated": 1,\
"validating": 1,\
"validation": 1,\
"validity": 1,\
"validly": 1,\
"variability": 1,\
"variable": 1,\
"variables": 1,\
"variably": 1,\
"variance": 1,\
"variant": 1,\
"variants": 1,\
"variation": 1,\
"variations": 1,\
"varied": 1,\
"varies": 1,\
"vary": 1,\
"varying": 1,\
"vehicle": 1,\
"vehicles": 1,\
"version": 1,\
"versions": 1,\
"via": 1,\
"violate": 1,\
"violated": 1,\
"violates": 1,\
"violating": 1,\
"violation": 1,\
"violations": 1,\
"virtual": 1,\
"virtually": 1,\
"visibility": 1,\
"visible": 1,\
"visibly": 1,\
"vision": 1,\
"visions": 1,\
"visual": 1,\
"visualisation": 1,\
"visualise": 1,\
"visualised": 1,\
"visualising": 1,\
"visualization": 1,\
"visualize": 1,\
"visualized": 1,\
"visualizing": 1,\
"visually": 1,\
"vol": 1,\
"volume": 1,\
"volumes": 1,\
"voluntarily": 1,\
"voluntary": 1,\
"volunteer": 1,\
"volunteered": 1,\
"volunteering": 1,\
"volunteers": 1,\
"welfare": 1,\
"whereas": 1,\
"whereby": 1,\
"widespread": 1}

with open("myAWLDict.txt", "wb") as myFile:
    pickle.dump(AWL, myFile)
