import pickle
from nltk.stem.snowball import SnowballStemmer

CSAWL ={"accelerate": 1,\
"activate": 1,\
"acyclic": 1,\
"adversary": 1,\
"affine": 1,\
"afore": 1,\
"algebra": 1,\
"algorithm": 1,\
"align": 1,\
"alphabet": 1,\
"amortise": 1,\
"annotate": 1,\
"anomaly": 1,\
"anonymous": 1,\
"arc": 1,\
"architecture": 1,\
"arithmetic": 1,\
"array": 1,\
"artifact": 1,\
"asynchronous": 1,\
"atom": 1,\
"audio": 1,\
"augment": 1,\
"authentic": 1,\
"authorise": 1,\
"automaton": 1,\
"autonomic": 1,\
"auxiliary": 1,\
"avail": 1,\
"axis": 1,\
"backup": 1,\
"bandwidth": 1,\
"barrier": 1,\
"baseline": 1,\
"batch": 1,\
"battery": 1,\
"bayesian": 1,\
"benchmark": 1,\
"binary": 1,\
"binomial": 1,\
"bitmap": 1,\
"boolean": 1,\
"bottleneck": 1,\
"breakdown": 1,\
"browse": 1,\
"budget": 1,\
"buffer": 1,\
"bug": 1,\
"byte": 1,\
"cache": 1,\
"calculus": 1,\
"calibrate": 1,\
"candidate": 1,\
"canonical": 1,\
"capture": 1,\
"cell": 1,\
"cellular": 1,\
"chip": 1,\
"chunk": 1,\
"churn": 1,\
"circuit": 1,\
"click": 1,\
"client": 1,\
"cluster": 1,\
"coefficient": 1,\
"cognitive": 1,\
"collaborate": 1,\
"collision": 1,\
"column": 1,\
"compact": 1,\
"compiler": 1,\
"compress": 1,\
"compromise": 1,\
"concrete": 1,\
"concurrency": 1,\
"configure": 1,\
"congest": 1,\
"conjecture": 1,\
"conjunction": 1,\
"consecutive": 1,\
"contend": 1,\
"contiguous": 1,\
"contour": 1,\
"contraction": 1,\
"converge": 1,\
"convex": 1,\
"convolute": 1,\
"corollary": 1,\
"corpus": 1,\
"correlate": 1,\
"corrupt": 1,\
"counter": 1,\
"cryptography": 1,\
"customise": 1,\
"database": 1,\
"dataset": 1,\
"deadline": 1,\
"debug": 1,\
"decentralize": 1,\
"decode": 1,\
"decompose": 1,\
"decrypt": 1,\
"dedicate": 1,\
"default": 1,\
"defect": 1,\
"degrade": 1,\
"delete": 1,\
"dense": 1,\
"departure": 1,\
"dependency": 1,\
"depict": 1,\
"deploy": 1,\
"descriptor": 1,\
"destination": 1,\
"diagnosis": 1,\
"diagonal": 1,\
"diagram": 1,\
"diameter": 1,\
"differential": 1,\
"digital": 1,\
"disc": 1,\
"discard": 1,\
"disclosure": 1,\
"disseminate": 1,\
"download": 1,\
"drawback": 1,\
"dual": 1,\
"efficacy": 1,\
"electronic": 1,\
"email": 1,\
"embed": 1,\
"embody": 1,\
"emergency": 1,\
"emotion": 1,\
"emulate": 1,\
"encode": 1,\
"encrypt": 1,\
"endpoint": 1,\
"enterprise": 1,\
"entropy": 1,\
"epoch": 1,\
"equilibrium": 1,\
"ethernet": 1,\
"execute": 1,\
"existential": 1,\
"exit": 1,\
"exponential": 1,\
"faculty": 1,\
"fake": 1,\
"feasible": 1,\
"feedback": 1,\
"fetch": 1,\
"filter": 1,\
"firewall": 1,\
"footprint": 1,\
"forum": 1,\
"fraction": 1,\
"fragment": 1,\
"functionality": 1,\
"fuse": 1,\
"fuzz": 1,\
"gadget": 1,\
"garbage": 1,\
"genetic": 1,\
"genre": 1,\
"geometry": 1,\
"gesture": 1,\
"ghost": 1,\
"gossip": 1,\
"gradient": 1,\
"granule": 1,\
"graph": 1,\
"grid": 1,\
"hammed": 1,\
"handshake": 1,\
"hardware": 1,\
"hash": 1,\
"header": 1,\
"healthcare": 1,\
"heterogeneous": 1,\
"heuristic": 1,\
"histogram": 1,\
"homogeneous": 1,\
"hop": 1,\
"horizontal": 1,\
"huge": 1,\
"hybrid": 1,\
"icon": 1,\
"identifier": 1,\
"incoming": 1,\
"increment": 1,\
"incur": 1,\
"indirect": 1,\
"inductive": 1,\
"infect": 1,\
"inject": 1,\
"inspire": 1,\
"install": 1,\
"instantiate": 1,\
"integer": 1,\
"interface": 1,\
"internet": 1,\
"interoperability": 1,\
"intersect": 1,\
"interview": 1,\
"intrusion": 1,\
"intuition": 1,\
"inverse": 1,\
"iterate": 1,\
"jitter": 1,\
"kernel": 1,\
"keyboard": 1,\
"laboratory": 1,\
"latent": 1,\
"lattice": 1,\
"layout": 1,\
"leak": 1,\
"legitimate": 1,\
"lemma": 1,\
"lever": 1,\
"linear": 1,\
"literal": 1,\
"locality": 1,\
"logarithm": 1,\
"lookup": 1,\
"loop": 1,\
"magnet": 1,\
"magnitude": 1,\
"malicious": 1,\
"mask": 1,\
"mathematics": 1,\
"matrix": 1,\
"maximal": 1,\
"median": 1,\
"merge": 1,\
"mesh": 1,\
"metadata": 1,\
"metric": 1,\
"microprocessor": 1,\
"mobile": 1,\
"modal": 1,\
"module": 1,\
"monotone": 1,\
"multicore": 1,\
"multilevel": 1,\
"multimedia": 1,\
"multimode": 1,\
"multithread": 1,\
"mutate": 1,\
"naive": 1,\
"navigate": 1,\
"negligible": 1,\
"neural": 1,\
"node": 1,\
"notate": 1,\
"novel": 1,\
"null": 1,\
"offline": 1,\
"offload": 1,\
"online": 1,\
"ontology": 1,\
"opt": 1,\
"optic": 1,\
"optimise": 1,\
"optimum": 1,\
"orthogonal": 1,\
"outgoing": 1,\
"outlying": 1,\
"outperform": 1,\
"overflow": 1,\
"overhead": 1,\
"overlay": 1,\
"overview": 1,\
"packet": 1,\
"pairwise": 1,\
"partition": 1,\
"password": 1,\
"payload": 1,\
"payoff": 1,\
"peak": 1,\
"peer": 1,\
"penalty": 1,\
"periphery": 1,\
"personalise": 1,\
"pervasive": 1,\
"phrase": 1,\
"pilot": 1,\
"pipeline": 1,\
"pixel": 1,\
"planar": 1,\
"platform": 1,\
"plot": 1,\
"polynomial": 1,\
"port": 1,\
"posterior": 1,\
"predecessor": 1,\
"predicate": 1,\
"prefix": 1,\
"primitive": 1,\
"privacy": 1,\
"probe": 1,\
"processor": 1,\
"profile": 1,\
"prominent": 1,\
"prone": 1,\
"propagate": 1,\
"proposition": 1,\
"prototype": 1,\
"proximity": 1,\
"prune": 1,\
"pulse": 1,\
"quadratic": 1,\
"quantify": 1,\
"query": 1,\
"queue": 1,\
"radius": 1,\
"recall": 1,\
"reconfigure": 1,\
"rectangle": 1,\
"recursive": 1,\
"redundant": 1,\
"regress": 1,\
"remote": 1,\
"render": 1,\
"replicate": 1,\
"repository": 1,\
"residue": 1,\
"resilience": 1,\
"retrieve": 1,\
"robust": 1,\
"rotate": 1,\
"rout": 1,\
"routine": 1,\
"runtime": 1,\
"scan": 1,\
"schema": 1,\
"score": 1,\
"script": 1,\
"segment": 1,\
"semantic": 1,\
"sensor": 1,\
"serial": 1,\
"session": 1,\
"setup": 1,\
"sibling": 1,\
"simulations": 1,\
"simultaneous": 1,\
"sketch": 1,\
"skip": 1,\
"slack": 1,\
"slot": 1,\
"smart": 1,\
"smartphone": 1,\
"snapshot": 1,\
"software": 1,\
"sophisticated": 1,\
"soundly": 1,\
"spam": 1,\
"span": 1,\
"sparse": 1,\
"spatial": 1,\
"spectre": 1,\
"spectrum": 1,\
"speedup": 1,\
"stack": 1,\
"static": 1,\
"stationary": 1,\
"stochastic": 1,\
"storage": 1,\
"subjective": 1,\
"subscribe": 1,\
"substrate": 1,\
"suffix": 1,\
"suite": 1,\
"superior": 1,\
"supervise": 1,\
"swap": 1,\
"switch": 1,\
"symmetry": 1,\
"synchronize": 1,\
"syntactic": 1,\
"syntax": 1,\
"synthesis": 1,\
"tablet": 1,\
"tag": 1,\
"template": 1,\
"temporal": 1,\
"testbed": 1,\
"texture": 1,\
"theorem": 1,\
"thermal": 1,\
"threshold": 1,\
"throughput": 1,\
"tier": 1,\
"timestamp": 1,\
"timing": 1,\
"token": 1,\
"tolerant": 1,\
"topology": 1,\
"traffic": 1,\
"transact": 1,\
"transient": 1,\
"transitive": 1,\
"transparent": 1,\
"traverse": 1,\
"triple": 1,\
"trivial": 1,\
"trustworthy": 1,\
"tuple": 1,\
"ubiquity": 1,\
"update": 1,\
"upload": 1,\
"usage": 1,\
"vector": 1,\
"velocity": 1,\
"verify": 1,\
"versus": 1,\
"vertex": 1,\
"vertical": 1,\
"vertice": 1,\
"vice": 1,\
"victim": 1,\
"video": 1,\
"virtualize": 1,\
"vocabulary": 1,\
"volt": 1,\
"vulnerable": 1,\
"wavelet": 1,\
"web": 1,\
"wireless": 1,\
"workflow": 1,\
"workload": 1,\
"workstation": 1}

#take stems from this list
CSAWL_stems = {}
stemmer = SnowballStemmer("english")
for token in CSAWL.keys():
    token = stemmer.stem(token)
    if token != "":
        CSAWL_stems[token] = 1
with open("myCSAWLDict.txt", "wb") as myFile:
    pickle.dump(CSAWL_stems, myFile)
